version: '3'


volumes:
  greyfish:


services:
  greyfish:
    build: .
    image: "greyfish/standalone"
    ports:
     - "2000-2003:2000-2003"
    volumes:
     - "greyfish:/greyfish"
    environment:
     - greyfish_key=greyfish
     - greyfish_path=/greyfish
    command: "tail -F anything"
