version: '2'


volumes:
  greyfish:
  influxdb:


services:

  greyfish:
    build: .
    image: "greyfish/standalone"

    ports:
     - "2000-2003:2000-2003"
    volumes:
     - "greyfish:/greyfish"

    extends:
      file: credentials.yml
      service: db_creds

    environment:
     - greyfish_key=greyfish
     - greyfish_path=/greyfish

    command: "tail -F anything"


  influxdb:
    image: "influxdb:latest"

    extends:
      file: credentials.yml
      service: db_creds

    ports:
      - "8083:8083"
      - "8086:8086"

    volumes:
      - "$PWD:/var/lib/influxdb"
      - "/srv/docker/influxdb/data:/var/lib/influxdb"

    command: "influxd"