+version: '2'


volumes:
  greyfish:
  influxdb:


services:


  greyfish:
    build: .
    image: "greyfish/standalone"

    ports:
      - "2000-2004:2000-2004"
    volumes:
      - "greyfish:/greyfish"

    environment:
      - greyfish_key=greyfish
      - greyfish_path=/greyfish
      - URL_BASE=0.0.0.0
    extends:
      file:
        credentials.yml
      service:
        db_creds

    command: "tail -F anything"


  # Define an InfluxDB service
  influxdb:
    image: influxdb:latest
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    ports:
      - "8086:8086"
      - "8083:8083"
    extends:
      file:
        credentials.yml
      service:
        db_creds
    command: "influxd"


  redis:
    image: 'redis:4-alpine'
    extends:
      file:
        credentials.yml
      service:
        db_creds
    command: redis-server --requirepass $REDIS_AUTH
    ports:
      - '6379:6379'
